### ISSUE TITLE
Error converting value "VIEW_ANOMALY_DETECTION_RESULTS"

### ISSUE THREAD

**Issue by mm93293rj** [rubrikinc/rubrik-powershell-sdk#108]
First time on GitHub...so not sure if i'm posting in the right place.

I'm getting the following error when trying to query RSC roles...could this be a SDK code issue?

Invoke-Rsc :
One or more errors occurred.
Error converting value "VIEW_ANOMALY_DETECTION_RESULTS" to type 'System.Nullable`1[RubrikSecurityCloud.Types.Operation]'. Path 'nodes[0].permissions[2].operation', line 1, position 275.

The query is:
query abc {
 getAllRolesInOrgConnection {
  nodes {
   id
   name
   permissions {
    operation
   }
  }
 }
}

 

SDK schema version is:
v20240422-15

**Comment by jakerobinson** [comment]
This is a disparity between the API and the SDK schemas. It should be fixed with the latest in the 1.5 release of the module. We're looking at ways to improve this issue in the future. Additionally, there's a new cmdlet called `Get-RscRole` which should make your life easier. :)

**Comment by mm93293rj** [comment]
Thank you very much Jake.
