### ISSUE TITLE
WARNING: Connect_Rsc: The installed RSC SDK version does not match the server version.

### ISSUE THREAD

**Issue by SahFari** [rubrikinc/rubrik-powershell-sdk#110]
Hi, 
I get 'WARNING: Connect_Rsc: The installed RSC SDK version does not match the server version.' when connecting to RSC.

Connect-Rsc -IfNeeded | Out-Null
WARNING: Connect_Rsc: The installed RSC SDK version does not match the server version.

$psversionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-InstalledModule RubrikSecurityCloud

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.4                  RubrikSecurityCloud                 PSGallery            PowerShell Module for Rubrik Security Cloud. GraphQL schema version: v20240506-29 .

Get-RscCluster

PauseStatus         : NOT_PAUSED
Status              : CONNECTED
SubStatus           : DEFAULT
SystemStatus        : WARNING
Type                : ON_PREM
Id                  : 
Name                : 
SystemStatusMessage : 1 Disk Down.
Version             : 9.1.1-p1-27720
Vars                : RubrikSecurityCloud.Types.Cluster+InlineVars

**Comment by jakerobinson** [comment]
This warning occurs when we have not updated the SDK with the latest schema from the API. Updating to the latest version of the module will fix this, and we're working on ways of improving this in the future.
