### ISSUE TITLE
Get-RscAccount is throwning an exception

### ISSUE THREAD

**Issue by csolje** [rubrikinc/rubrik-powershell-sdk#12]
![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/3214200/e6f62482-3128-4939-ac20-3ce385e3003f)

```PowerShell
Invoke-RscQueryAccount: Exception has been thrown by the target of an invocation. Inner exception: One or more errors occurred. (API Server error: OK   Query: query QueryAccountId{accountId  __typename }   Variables: {}  )
```

It does output values, but it is throwning that exception

**Comment by guirava** [comment]
thank you for your feedback. Please update your SDK install and this issue should be gone.
