### ISSUE TITLE
Filter not working ??

### ISSUE THREAD

**Issue by Freakwncy** [rubrikinc/rubrik-powershell-sdk#13]
PS C:\Users\rhobbs> _$a=invoke-rsc -query "query GlobalSearchObjectQuery{globalSearchResults(first: 1000){edges {cursor node {id name objectType logicalPath{fid name objectType}}}}}"_ 

PS C:\Users\rhobbs> _$a.edges.node | Measure-Object_

Count             : 1000
Average           : 
Sum               : 
Maximum           : 
Minimum           : 
StandardDeviation : 
Property          :

PS C:\Users\rhobbs> _$a=invoke-rsc -query "query GlobalSearchObjectQuery{globalSearchResults(filter:[{texts: ["USTRY1METV06B4"] }]){edges {cursor node {id name objectType logicalPath{fid name objectType}}}}}"_
**Invoke-Rsc: Exception has been thrown by the target of an invocation.**
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
All I did was replace first: 1000 with a filter.

globalSearchResults(
first: [Int](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/int.doc.html),
after: [String](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/string.doc.html),
last: [Int](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/int.doc.html),
before: [String](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/string.doc.html),
sortBy: [HierarchySortByField](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/hierarchysortbyfield.doc.html),
sortOrder: [SortOrder](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/sortorder.doc.html),
filter: [[Filter](https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/filter.doc.html)!]
)

**Comment by guirava** [comment]
Scrubbing old issues ... I believe this is resolved, please re-open if not.
