### ISSUE TITLE
Choosing replication target when restoring SQL database

### ISSUE THREAD

**Issue by baloobaloo** [rubrikinc/rubrik-powershell-sdk#153]
In my script I'm using New-RscMssqlExport command to run restore for several databases as a part of backup verification. 
It runs fine for SQL backups on cluster A. Some of the databases are replicated from cluster A to cluster B.
I would like to test the replicated copies from cluster B. Is it possible to run it using GraphQL API and current SDK version?

**Comment by clumnah** [comment]
Yes it is. See this Notebook on the workflow for exporting a database. I explain it and the steps to an export. 
https://github.com/clumnah/Operationalize-MSSQL-Backups-With-Rubrik-Security-Cloud/blob/main/content/New-RscMssqlExport.ipynb

**Comment by baloobaloo** [comment]
Perfect! that's what I was looking for.
Thank you!
