### ISSUE TITLE
Get-RSCVsphereVm Fails to Find Some VMs Using Name

### ISSUE THREAD

**Issue by therealgill** [rubrikinc/rubrik-powershell-sdk#2]
Description:
I noticed that _Get-RSCVsphereVm -Name 'Example VM Name'_ was not finding the VM in question. After manually getting the Object ID from RSC I was able to get the VM information using _Get-RSCVsphereVm -Id 'Example ID'_ . When trying to send the Name back to the cmdlet I received the below error.

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/16581649/e524c0c9-9f9b-4376-a67d-ee1c56c9b455)

Output:
![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/16581649/64b31191-c90b-43c0-9e0c-e478190efec2)

Raw Error Text: 
One or more errors occurred. (Could not serialize variables : System.ArgumentException: Object serialized to Array. JObject instance expected.    at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer) at RubrikSecurityCloud.OperationVariableSet.AsJson(IRscLogger logger) in /Users/guirava/src/sdmain/polaris/src/rubrik/clients/sdks/rubrik-powershell-sdk/rubrik-powershell-sdk/RubrikSecurityCloud/RubrikSecurityCloud.CommonSerializer) at/OperationVariableSet.cs:line 86 at                                                                                                                                                                                           /OperationVariableSet.cs:line 86 at RubrikSecurityCloud.NetSDK.Client.RscGraphQLClient.InvokeGenericCallAsync[T](GraphQLRequest request, OperationVariableSet variables, IRscLogger logger, Dictionary`2 metricsTags) in /Users/guirava/src/sdmain/polaris/src/rubrik/clients/sdks/rubrik-powershell-sdk/rubrik-powershell-sdk/RubrikSecurityCloud/RubrikSecurityCloud.Client/RscGraphQLClientGenericCall.cs:line 137)

**Comment by therealgill** [comment]
Additionally, _Get-RscVsphereVm | Where-Object { $_.Name -eq $vmFromID.Name }_  does not return any results.

**Comment by rynardtspies** [comment]
Hi @therealgill 

We did pick up on this issue internally earlier this week, and I am happy to report that this issue has been addressed and the fix will be included in the next increment of the beta release.

Regards

Rynardt

**Comment by rynardtspies** [comment]
Issue resolved in 0.8.0
