### ISSUE TITLE
Naming in JSON file from RSC and powershell module does not match

### ISSUE THREAD

**Issue by patwolf99** [rubrikinc/rubrik-powershell-sdk#29]
I had problems to use the function "Set-RscServiceAccountFile" as i got the failure message " Cannot bind argument to parameter 'String' because it is null.".

After two ours of troubleshooting I found the issue.

The json file, which you download from RSC UI, has a diffrent naming convention as in the powershell function.
For example:
Json file: "ClientId"
function: "client_id"

Thanks for checking that out!

**Comment by guirava** [comment]
Thank you for your feedback. Fixed in 0,30.
