### ISSUE TITLE
'Invoke-Rsc -Query' returns scaffolded object with nulls, even if query does not return data

### ISSUE THREAD

**Issue by therealgill** [rubrikinc/rubrik-powershell-sdk#3]
This may be 'as designed'. If so, please ignore.

Description:

When running an 'Invoke-Rsc -Query' command and specifying a subset of the attributes to be returned, additional attributes are returned as null. For instance:
![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/16581649/8814223b-390e-4134-a5a3-879c64b7a3d8)

Notice how only node.id and node.name were requested, but Count, Edges, and PageInfo were returned. Likewise...
![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/16581649/88544dfa-209f-4b04-9335-be08a9aa6496)

The node objects in the collection also have unrequested attributes (node.GuestOsType, node.ProtectionDate, node.Cluster, as well as all other hidden properties).

**Comment by guirava** [comment]
Thank you for your feedback. Your question generated a new entry in the FAQ:

https://github.com/rubrikinc/rubrik-powershell-sdk/blob/main/docs/faq.md#faq2-nulls-in-response
