### ISSUE TITLE
No detailed help in Connect-RSC

### ISSUE THREAD

**Issue by mwpreston** [rubrikinc/rubrik-powershell-sdk#36]
The `Connect-RSC` cmdlet doesn't contain detailed help within PowerShell.  At the very least I feel like we should have examples listed on how to connect using each method

**Comment by guirava** [comment]
Thanks for finding this; this regressed, there used to be fairly decent docs for it as you can see here:
https://github.com/rubrikinc/rubrik-powershell-sdk/blob/main/RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/Connect-Rsc.cs

but it looks like the script that exports xml comments to doc is not doing its job . I filed a story internally.

**Comment by rynardtspies** [comment]
Fix has been applied to the dev build and will be included in an upcoming release
