### ISSUE TITLE
Improve Invoke-RSC help

### ISSUE THREAD

**Issue by doslagerRubrik** [rubrikinc/rubrik-powershell-sdk#44]
Possible duplicate of issue #14 

The help output to Invoke-RSC needs better explanation and examples. 

It's unclear what the difference between `-GqlQuery` and `-Query` is. There is no example of `-Query`. Maybe the `-GqlQuery` param should just be `-Query`? Shouldnt all queries submitted be in native GQL format? Or is there a different way to submit a native GQL query as an object?

**Comment by guirava** [comment]
Thank you for the feedback. Improved in 0.30. Please re-open if still an issue.
