### ISSUE TITLE
Get-RscEventSeries does not return the event ID

### ISSUE THREAD

**Issue by krobar1** [rubrikinc/rubrik-powershell-sdk#5]
I checked the get-help for this module with examples, and the command fails.  From what I can tell the command should work.

PS C:\Users\jwebb6> get-help get-rsceventseries -examples 

NAME
    Get-RscEventSeries

SYNOPSIS
    Retrieve RSC events.

    -------------------------- EXAMPLE 1 --------------------------

    PS > Get-RscEventSeries -First 3
    Id IsCancelable IsPolarisEventSeries LastActivityStatus
    -- ------------ -------------------- ------------------
    24738        False                 True            SUCCESS
    24736        False                 True            SUCCESS
    24731        False                 True            SUCCESS

    This example lists the first 3 events.

    -------------------------- EXAMPLE 2 --------------------------

    PS > (Get-RscEventSeries -First 3).Id
    24738
    24736
    24731

    This example lists the first 3 events, and only get their ids.

    -------------------------- EXAMPLE 3 --------------------------

    PS > $firstId = (Get-RscEventSeries -First 1 -Detail).ActivitySeriesId

    Saves the first id.

    -------------------------- EXAMPLE 4 --------------------------

    PS > Get-RscEventSeries -Id $firstId -Detail

    Retrieves an event series by ID.

    -------------------------- EXAMPLE 5 --------------------------

    PS > ActivitySeriesId     : e4c274e5-a096-4464-89a4-4771492baf00
    ClusterName          : Polaris
    ClusterUuid          : 00000000-0000-0000-0000-000000000000
    Fid                  : e4c274e5-a096-4464-89a4-4771492baf00
    Id                   : 24738
    IsCancelable         : False
    IsPolarisEventSeries : True
    LastEventAddedAt     : 4/12/2023 10:18:06 PM
    LastUpdated          : 4/12/2023 10:18:06 PM
    Location             :
    ObjectId             : e4c274e5-a096-4464-89a4-4771492baf00
    ObjectName           : cdm-cluster-fvvvch-rrjkitw
    OrgName              :
    Progress             : 100%
    StartTime            : 4/12/2023 10:02:17 PM
    LastActivityStatus   : SUCCESS
    LastActivityType     : CONFIGURATION
    ObjectType           : CLUSTER
    Severity             : INFO

    Retrieves an event series by ID, with details.

PS C:\Users\jwebb6>
PS C:\Users\jwebb6> $firstId = (Get-RscEventSeries -First 1 -Detail).ActivitySeriesId
Invoke-RscQueryActivitySeries: Exception has been thrown by the target of an invocation. Inner exception: One or more errors occurred. (API Server error: OK   Query: query
QueryActivitySeriesConnection($first: Int,$after: String,$last: Int,$before: String,$sortOrder: SortOrder,$sortBy: ActivitySeriesSortField,$filters:
ActivitySeriesFilter) {activitySeriesConnection ( first: $first after: $after last: $last before: $before sortOrder: $sortOrder sortBy: $sortBy filters: $filters  
){   count   nodes {     lastActivityStatus     lastActivityType     objectType     severity     activitySeriesId     causeErrorCode     causeErrorMessage
causeErrorReason     causeErrorRemedy     clusterName     clusterUuid     dataTransferred     effectiveThroughput     failureReason     fid     id
isCancelable     isPolarisEventSeries     lastEventAddedAt     lastUpdated     lastVerifiedAt     location     logicalSize     objectId     objectName     orgId   
orgName     progress     startTime     activityConnection {       count       nodes {         objectType         severity         status         type
activityInfo         clusterId         id         message         objectId         progress         time        __typename }       pageInfo {         endCursor    
hasNextPage         hasPreviousPage         startCursor        __typename }      __typename }     cluster {       licensedProducts       pauseStatus
productType       registeredMode       status       subStatus       systemStatus       type       connectivityLastUpdated       defaultAddress       defaultPort   
encryptionEnabled       estimatedRunway       id       isHealthy       lastConnectionTime       name       noSqlWorkloadCount       passesConnectivityCheck        
registrationTime       snapshotCount       systemStatusMessage       timezone       version      __typename }     organizations {       authDomainConfig
tenantNetworkHealth       allUrls       allowedClusters       description       fullName       hasOwnIdpConfigured       id       isEnvoyRequired       name       
physicalStorageUsed       shouldEnforceMfaForAll      __typename }    __typename }   pageInfo {     endCursor     hasNextPage     hasPreviousPage     startCursor  
__typename }  __typename }  __typename }   Variables: {"first":1}  )

Remove-NullProperties: Cannot bind argument to parameter 'Object' because it is null.

PS C:\Users\jwebb6>

**Comment by Freakwncy** [comment]
After 3 mins. I got this error.
PS C:\temp> (Get-RscEventSeries -First 3).Id
Invoke-RscQueryActivitySeries: Exception has been thrown by the target of an invocation. Inner exception: One or more errors occurred. (API Server error: OK   Query: query QueryActivitySeriesConnection($first: Int,$after:
String,$last: Int,$before: String,$sortOrder: SortOrder,$sortBy: ActivitySeriesSortField,$filters: ActivitySeriesFilter) {activitySeriesConnection ( first: $first after: $after last: $last before:
$before sortOrder: $sortOrder sortBy: $sortBy filters: $filters ){   count   nodes {     lastActivityStatus     objectType     id     isCancelable     isPolarisEventSeries    __typename }
pageInfo {     endCursor     hasNextPage     hasPreviousPage     startCursor    __typename }  __typename }  __typename }   Variables: {"first":3}  )

Remove-NullProperties: Cannot bind argument to parameter 'Object' because it is null.

PS C:\temp>

**Comment by guirava** [comment]
Scrubbing old issues ... I believe this is resolved, please re-open if not.
