### ISSUE TITLE
Backup-SlaDomain : The term 'Backup-SlaDomain' is not recognized as the name of a cmdlet stopped working in 0.26 version

### ISSUE THREAD

**Issue by notaworker** [rubrikinc/rubrik-powershell-sdk#50]
.EXAMPLE
Backup-SlaDomain -SlaDomainAssignType "PROTECT_WITH_SLA_ID" -SlaOptionalId "00000000-0000-0000-0000-000000000000" -ObjectIds @("31012362-0ca8-5536-8c1a-313d756396c3")

Seems that the Backup-SlaDomain stopped working after upgrading to 0.26 from 0.24 (worked fine).
PS J:\> Backup-SlaDomain
Backup-SlaDomain : The term 'Backup-SlaDomain' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verif
y that the path is correct and try again.
At line:1 char:1
+ Backup-SlaDomain
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Backup-SlaDomain:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS J:\> Get-Module -ListAvailable -Name RubrikSecurityCloud

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.26       RubrikSecurityCloud                 {New-RscMutationCrossAccount, New-RscMutationFileset, New-RscMutationNas, New-RscQueryHyperv...}

Thanks

**Comment by guirava** [comment]
Thank you for your feedback - `Backup-SlaDomain` was renamed `Backup-RscSlaDomain` to follow the PowerShell naming scheme.
