### ISSUE TITLE
0.26/0.25 not installing correctly on RedHat 8.9 / Pwsh 7.4.1

### ISSUE THREAD

**Issue by xenonchris** [rubrikinc/rubrik-powershell-sdk#52]
We've been using 0.24 without issue but while migrating a backup scripts to a new machine we encountered the following issues with 0.26:

PS /home/user> Install-Module -Name RubrikSecurityCloud -Scope CurrentUser -Force
PS /home/user> Import-Module RubrikSecurityCloud
PS /home/user> Set-RscServiceAccountFile "/home/user/ServiceSecret.json"
Set-RscServiceAccountFile: Unable to save credentials to : Unable to find type [RubrikSecurityCloud.Files].
PS /home/user> exit
perforce@server:/ pwsh
PowerShell 7.4.1
PS /home/user> Import-Module RubrikSecurityCloud
Write-Error: Unable to load Rubrik Security Cloud Module: The specified module '/home/user/.local/share/powershell/Modules/RubrikSecurityCloud/0.26/net6.0/RubrikSecurityCloud.PowerShell.Dll' was not loaded because no valid module file was found in any module directory.

0.26/0.25 simply wont install or load cleanly on our RHEL 8.9 instances.

Rolling back to 0.24 that's on our other instances everything works as expected:
PS /home/user> Uninstall-Module -Name RubrikSecurityCloud
PS /home/user> Install-Module -Name RubrikSecurityCloud -RequiredVersion 0.24 -force
PS /home/user> Import-Module RubrikSecurityCloud
PS /home/user> Set-RscServiceAccountFile "/home/user/ServiceSecret.json"

Creating credential store...

Reading RSC Service Account JSON File from /home/user/ServiceSecret.json

Saving credential file: //SNIP

Issue persists in 0.25, 0.24 is working every time for us.

**Comment by guirava** [comment]
Thank you for your feedback and sorry about the delay; fixed in 0.30. Please re-open if issues remain.
