### ISSUE TITLE
Get-RscNasShare? 

### ISSUE THREAD

**Issue by SahFari** [rubrikinc/rubrik-powershell-sdk#54]
Hi,

Is there a cmdlet for NAS Shares in RSC? Get-RubrikNASShare doesn’t show any NAS share since the we migrated to RSC from CDM.

Cannot find NAS under the FileList in [PowerShell Gallery | RubrikSecurityCloud](https://www.powershellgallery.com/packages/RubrikSecurityCloud/0.26)

I need to change the script that we use in our monitoring system, SCOM.

**Comment by clumnah** [comment]
Take a look at the `New-RscQueryNas -Operation Share` query to see if that gives you what you need.

**Comment by SahFari** [comment]
Hi Chris,


I did not get the results I wanted
New-RscQueryNas -Operation Share


Op    Var                  Field
--    ---                  -----
Share {[fid, [vardict]{}]} RubrikSecurityCloud.Types.NasShare


What I want to see is the list of shares and there status

This is how we monitor their status in SquardUp.

$nasshare=Get-RubrikNASShare
$nasshare | add-member -membertype Noteproperty "state" -Value ""
foreach ($nas in $nasshare){
    $nas.state = if ($nas.status -eq "Connected")
    {'Healthy'}
    else
    {'Critical'}
  }
  $nasshare | sort-object name

Med vänlig hälsning
Fari Sah

Fari Sah  |  IT-tekniker
Skogsstyrelsen  |  IT-enheten
55183 Jönköping
036-35 93 00 (växel)  |  036-35 94 31 (direkt)
***@***.******@***.***>  |  skogsstyrelsen.se<https://skogsstyrelsen.se/>
Så behandlar vi personuppgifter<https://skogsstyrelsen.se/gdpr>

***@***.***

Från: Chris Lumnah ***@***.***>
Skickat: den 19 mars 2024 19:06
Till: rubrikinc/rubrik-powershell-sdk ***@***.***>
Kopia: Sah Fari IT-enheten ***@***.***>; Author ***@***.***>
Ämne: [EXTERNT] Re: [rubrikinc/rubrik-powershell-sdk] Get-RscNasShare? (Issue #54)


Take a look at the New-RscQueryNas -Operation Share query to see if that gives you what you need.

**Comment by clumnah** [comment]
The cmd I was providing was the high level cmd to allow you to dig deeper into what you may be after. For just a list of your NAS shares, look at the below.

```
$query = New-RscQueryNas -Operation Systems
$query.invoke().nodes
```

**Comment by guirava** [comment]
`Get-RscNasShare` will be release in version 1.1 , please re-open issue if you're still running into problems.
