### ISSUE TITLE
Get-RscCluster throws an exception

### ISSUE THREAD

**Issue by krobar1** [rubrikinc/rubrik-powershell-sdk#7]
The Get-RscCluster command will throw an exception when getting all of the clusters.  If a number of 8 or less is specified the command works.

PS C:\Users\jwebb6> Get-RscCluster                                                                       
Invoke-RscQueryCluster: Exception has been thrown by the target of an invocation. Inner exception: One or more errors occurred. (API Server error: OK   Query: query QueryClusterConnection($first: Int,$after: String,$last:
Int,$before: String,$filter: ClusterFilterInput,$sortOrder: SortOrder,$sortBy: ClusterSortByEnum) {clusterConnection ( first: $first after: $after last: $last before: $before filter: $filter
sortOrder: $sortOrder sortBy: $sortBy ){   nodes {     pauseStatus     status     subStatus     systemStatus     type     id     isHealthy     name     systemStatusMessage     version    __typename }  
__typename }  __typename }   Variables: {"first":1000}  )
 
PS C:\Users\jwebb6>

PS C:\chef-repo\cookbooks> $c=Get-RscCluster -First 8
item.Key: first, item.Value: 8 type: System.Int32

PS C:\chef-repo\cookbooks> $c=Get-RscCluster -First 9
item.Key: first, item.Value: 9 type: System.Int32
Invoke-RscQueryCluster: **Exception** has been thrown by the target of an invocation. 

PS C:\chef-repo\cookbooks> Get-RscCluster
item.Key: first, item.Value: 1000 type: System.Int32
Invoke-RscQueryCluster: **Exception** has been thrown by the target of an invocation.

**Comment by rynardtspies** [comment]
Hi @krobar1 

I've had a look at my environment and I am unable to reproduce this.

What version of the RubrikSecurityCloud module do you have installed?

`Get-Module RubrikSecurityCloud |Select-Object Version`

Regards

Rynardt

**Comment by Freakwncy** [comment]
PS C:\temp> get-module -name RubrikSecurityCloud | Select-object version

Version
-------
0.8.0

**Comment by rynardtspies** [comment]
```powershell
PS /Users/rynardtspies> (Get-RscCluster).Count
18
PS /Users/rynardtspies> Get-RscCluster -First 8 | Select Id

Id
--
9b429c53-2afe-44b5-b4e4-e3a4308a69fb
fd326eaa-534d-4f2a-861e-250d192fbaae
f76a2f28-7d30-461f-9bbe-0e5e88c63405
0441bdf2-efc0-4f3e-bacd-b2ceaeb66a8b
14edc1b8-f13d-4548-8fa1-0ed7c7173bed
becf11c9-5a8f-4e3d-b7d7-630394b02a03
59cf578d-3a27-4df2-83f4-472e1b54b314
e5c7d751-18ea-4e16-a92d-eac7252106d5

PS /Users/rynardtspies> Get-RscCluster -First 9 | Select Id

Id
--
9b429c53-2afe-44b5-b4e4-e3a4308a69fb
fd326eaa-534d-4f2a-861e-250d192fbaae
f76a2f28-7d30-461f-9bbe-0e5e88c63405
0441bdf2-efc0-4f3e-bacd-b2ceaeb66a8b
14edc1b8-f13d-4548-8fa1-0ed7c7173bed
becf11c9-5a8f-4e3d-b7d7-630394b02a03
59cf578d-3a27-4df2-83f4-472e1b54b314
e5c7d751-18ea-4e16-a92d-eac7252106d5
179996b2-7dcf-4d81-b8e7-96b4fdc1dc22

PS /Users/rynardtspies> Get-RscCluster -First 18 | Select Id

Id
--
9b429c53-2afe-44b5-b4e4-e3a4308a69fb
fd326eaa-534d-4f2a-861e-250d192fbaae
f76a2f28-7d30-461f-9bbe-0e5e88c63405
0441bdf2-efc0-4f3e-bacd-b2ceaeb66a8b
14edc1b8-f13d-4548-8fa1-0ed7c7173bed
becf11c9-5a8f-4e3d-b7d7-630394b02a03
59cf578d-3a27-4df2-83f4-472e1b54b314
e5c7d751-18ea-4e16-a92d-eac7252106d5
179996b2-7dcf-4d81-b8e7-96b4fdc1dc22
120a6149-7801-4f0a-a1b8-d4c31a45b580
9644dbd8-05af-4c3a-ad0e-3c9d4efd0381
275dee9e-8ed0-4f3d-ae2b-e35f3e940290
a6e806b6-0996-4163-a80d-493a2dded214
17cc48a2-1886-4690-8cea-d29d4b03e8a6
fc8a1048-0c31-4275-b87d-27e5bba6fe32
b15eb632-edca-408b-817d-abe450c89447
f51a81a4-26c4-4637-9595-f25a765b8c67
011cc51c-a98f-4391-a8c4-a9c1ca20ff58

PS /Users/rynardtspies> Get-RscCluster -First 200 | Select Id

Id
--
9b429c53-2afe-44b5-b4e4-e3a4308a69fb
fd326eaa-534d-4f2a-861e-250d192fbaae
f76a2f28-7d30-461f-9bbe-0e5e88c63405
0441bdf2-efc0-4f3e-bacd-b2ceaeb66a8b
14edc1b8-f13d-4548-8fa1-0ed7c7173bed
becf11c9-5a8f-4e3d-b7d7-630394b02a03
59cf578d-3a27-4df2-83f4-472e1b54b314
e5c7d751-18ea-4e16-a92d-eac7252106d5
179996b2-7dcf-4d81-b8e7-96b4fdc1dc22
120a6149-7801-4f0a-a1b8-d4c31a45b580
9644dbd8-05af-4c3a-ad0e-3c9d4efd0381
275dee9e-8ed0-4f3d-ae2b-e35f3e940290
a6e806b6-0996-4163-a80d-493a2dded214
17cc48a2-1886-4690-8cea-d29d4b03e8a6
fc8a1048-0c31-4275-b87d-27e5bba6fe32
b15eb632-edca-408b-817d-abe450c89447
f51a81a4-26c4-4637-9595-f25a765b8c67
011cc51c-a98f-4391-a8c4-a9c1ca20ff58

PS /Users/rynardtspies> Get-Module -Name RubrikSecurityCloud | Select-Object Version

Version
-------
0.8.0
```

**Comment by guirava** [comment]
Thank you for your feedback . It was identified this was not an SDK issue but an issue with the deployment.
