### ISSUE TITLE
Trying to get the ConfiguredSlaDomain from the command Get-RscMssqlInstance -HostName but gets null

### ISSUE THREAD

**Issue by notaworker** [rubrikinc/rubrik-powershell-sdk#70]
When running Get-RscMssqlInstance -HostName 10.36.45.1 -Debug we can see the assigned SLA but not with the regular command, then its null.
Any ideas why? BUG?

Get-RscMssqlInstance -HostName 10.36.45.1

AuthorizedOperations              :
ObjectType                        : MSSQL_INSTANCE
SlaAssignment                     : DIRECT
ConfiguredSlaDomain               :
EffectiveRetentionSlaDomain       :
EffectiveSlaDomain                : RubrikSecurityCloud.Types.GlobalSlaReply
PendingSla                        :
ReplicatedObjects                 :
HasLogConfigFromSla               : True
HostLogRetention                  :
Id                                : 92cde7-a83a-56cb-a355-3138d54
LogBackupFrequencyInSeconds       :
LogBackupRetentionInHours         :
Name                              : MSSQLSERVER
NumWorkloadDescendants            : 5
ReplicatedObjectCount             :
SlaPauseStatus                    : False
UnprotectableReasons              :
AllOrgs                           :
Cluster                           : RubrikSecurityCloud.Types.Cluster
CrossAccountReplicatedObjectInfos :
DescendantConnection              :
EffectiveSlaSourceObject          :
LatestUserNote                    :
LogicalChildConnection            :
LogicalPath                       :
PendingObjectDeletionStatus       :
PhysicalPath                      : {10.36.45.1}
PrimaryClusterLocation            :
SnapshotDistribution              :
Vars                              : RubrikSecurityCloud.Types.MssqlInstance+InlineVars

**Comment by clumnah** [comment]
The SLA that is in effect can be found in the EffectiveSLADomain object. In that object you can see the ID and Name of the SLA that is currently assigned to the object and in use. 

Closing this issue out, reopen if this needs an additional fix.
