### ISSUE TITLE
Running Get-RscMssqlAvailabilityGroup for a specific, known good ID returns no results and no error

### ISSUE THREAD

**Issue by clumnah** [rubrikinc/rubrik-powershell-sdk#74]
Running Get-RscMssqlAvailabilityGroup for a specific, known good ID returns no results and no error.

**Comment by SahFari** [comment]
I get the same results (no results!) here.
It works with Get-RscMssqlAvailabilityGroup -AvailabilityGroupName

I have installed version 1.0.

**Comment by clumnah** [comment]
I have a fix submitted to address this.

**Comment by SahFari** [comment]
It works fine in 1.1 👍🏼 
Thanks!

**Comment by SahFari** [comment]
Installed 1.1 this morning.
This works Get-RscMssqlAvailabilityGroup -AvailabilityGroupName 
This dosen't Get-RscMssqlAvailabilityGroup -Id

**Comment by clumnah** [comment]
Confirmed this is resolved in 1.3 as it works in 7.4.2
