### ISSUE TITLE
Get-RscMssqlDatabase -Name doesn’t work for user having a custom role

### ISSUE THREAD

**Issue by SahFari** [rubrikinc/rubrik-powershell-sdk#77]
I have a Service Account that has custom role assigned to it in RSC. 

User:
This user is going to be used in automation, mostly export and live mounts.

Role:
This Role can take on-demand snapshots, export and mount all SQL Databases.

This command returns no info:
Get-RscMssqlDatabase -Name Test

This returns all info:
Get-RscMssqlDatabase -List | Where-Object {$_.Name -eq 'Test'}

I get results for both commands when I run the same script with a user that have admin role in 
RSC 

I am running version 1.0. CDM version: 8.1.3-p7.

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/74422308/2138306d-6759-41d0-a1fa-fc157922c64f)

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/74422308/799e072e-cf96-48c9-aebd-e15a3b35cc77)

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/74422308/c05da795-14a6-44f1-87fd-6ac1ec52d001)

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/74422308/94f93dd8-7736-4553-8e7c-01afe19092e8)

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/74422308/954569a9-a689-4931-a001-0c9ebeff3bb4)

![image](https://github.com/rubrikinc/rubrik-powershell-sdk/assets/74422308/712f1dc4-ebee-45a5-9c8a-725d0610057b)

**Comment by clumnah** [comment]
I do not believe this issue has anything to do with RBAC. Based on how you were using the cmdlet, I was able to recreate the issue as an admin. I have a fix deployed to the devel branch and when a PR is merged it will be available to all.

**Comment by SahFari** [comment]
In works in PSVersion 7.4.2 and 7.3.9 after upgrading to 1.2 👍🏼 

Tnx
