### ISSUE TITLE
Default Address and Port does not return when called

### ISSUE THREAD

**Issue by Freakwncy** [rubrikinc/rubrik-powershell-sdk#8]
Invoke-Rsc "query {clusterConnection{nodes{name, defaultAddress, defaultPort}}}" | Select -ExpandProperty Nodes

Returns only the name and not the default address and port.

LicensedProducts                : 
PauseStatus                     : 
ProductType                     : 
RegisteredMode                  : 
Status                          : 
SubStatus                       : 
SystemStatus                    : 
Type                            : 
ConnectivityLastUpdated         : 
DefaultAddress                  : 
DefaultPort                     : 
EncryptionEnabled               : 
EstimatedRunway                 : 
Id                              : 
IsHealthy                       : 
LastConnectionTime              : 
Name                            : AEAUH11RBRKBU01A
NoSqlWorkloadCount              : 
PassesConnectivityCheck         : 
RegistrationTime                : 
SnapshotCount                   : 
SystemStatusMessage             : 
Timezone                        : 
Version                         : 
ActivitySeriesConnection        : 
AllOrgs                         : 
AuthorizedOperations            : 
CcprovisionInfo                 : 
CdmClusterNodeDetails           : 
CdmUpgradeInfo                  : 
CloudInfo                       : 
ClusterDiskConnection           : 
ClusterNodeConnection           : 
ClusterNodeStats                : 
ConfigProtectionInfo            : 
DatagovAutoEnablePolicyConfig   : 
DatagovPreviewerConfig          : 
GeoLocation                     : 
GlobalManagerConnectivityStatus : 
LambdaConfig                    : 
LambdaFeatureHistory            : 
MetadataPullScheduler           : 
Metric                          : 
MetricTimeSeries                : 
ReplicationSources              : 
ReplicationTargets              : 
RubrikSyncStatus                : 
SnappableConnection             : 
State                           : 
SystemStatusAffectedNodes       :

**Comment by guirava** [comment]
Thank you for your feedback. A FAQ entry was written about this issue:

https://github.com/rubrikinc/rubrik-powershell-sdk/blob/main/docs/faq.md
