### ISSUE TITLE
Protect-RscSnappable seems to replace Backup-RscSlaDomain

### ISSUE THREAD

**Issue by IamTHEvilONE** [rubrikinc/rubrik-powershell-sdk#81]
1. There is no release note stating that the old commandlet was deprecated/broken.
2. The new function wasn't mentioned that Protect-RscSnappable is the replacement.
3. The name `Protect-RscSnappable` isn't ideal.  It should be something like `Protect-RscWorkload` to align to the verbiage used in the GUI:
<img width="405" alt="image" src="https://github.com/rubrikinc/rubrik-powershell-sdk/assets/2575419/fbc96f37-1743-44d2-b159-cbc440d3a695">

**Comment by guirava** [comment]
Thank you for your feedback , the cmdlet will be renamed in upcoming version 1.1

**Comment by jakerobinson** [comment]
PR #84
