### ISSUE TITLE
Cluster Ipmi not working

### ISSUE THREAD

**Issue by Freakwncy** [rubrikinc/rubrik-powershell-sdk#9]
Can't figure out how to get the cmdlet to run properly.

PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi(id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee")}" -debug                                         
DEBUG: [Invoke_Rsc] RscBasePSCmdlet.cs:90:BeginProcessing()
  Cmdlet Inputs:
    Query (String): query {clusterIpmi(id:
    Op (String): 79f40f9f-3e63-4639-b9d1-f32a1022f6ee)}
    InputProfile (Profile): DEFAULT

Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpMapping(clusterUuid: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee")}" -debug
DEBUG: [Invoke_Rsc] RscBasePSCmdlet.cs:90:BeginProcessing()
  Cmdlet Inputs:
    Query (String): query {clusterIpMapping(clusterUuid:
    Op (String): 79f40f9f-3e63-4639-b9d1-f32a1022f6ee)}
    InputProfile (Profile): DEFAULT

Invoke-Rsc: Object reference not set to an instance of an object.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi(input: {GetIpmiInput{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"}})}"                         
Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi(input: {GetIpmiInput{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"}})}" -debug
DEBUG: [Invoke_Rsc] RscBasePSCmdlet.cs:90:BeginProcessing()
  Cmdlet Inputs:
    Query (String): query {clusterIpmi(input: {GetIpmiInput{id:
    Op (String): 79f40f9f-3e63-4639-b9d1-f32a1022f6ee}})}
    InputProfile (Profile): DEFAULT

Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi(GetIpmiInput{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"}})}" -debug        
DEBUG: [Invoke_Rsc] RscBasePSCmdlet.cs:90:BeginProcessing()
  Cmdlet Inputs:
    Query (String): query {clusterIpmi(GetIpmiInput{id:
    Op (String): 79f40f9f-3e63-4639-b9d1-f32a1022f6ee}})}
    InputProfile (Profile): DEFAULT

Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi(GetIpmiInput{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"})}" -debug 
DEBUG: [Invoke_Rsc] RscBasePSCmdlet.cs:90:BeginProcessing()
  Cmdlet Inputs:
    Query (String): query {clusterIpmi(GetIpmiInput{id:
    Op (String): 79f40f9f-3e63-4639-b9d1-f32a1022f6ee})}
    InputProfile (Profile): DEFAULT
Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi(GetIpmiInput{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"})}"
Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"})}"             
Invoke-Rsc: Exception has been thrown by the target of an invocation.
PS C:\Users\rhobbs> Invoke-Rsc "query {clusterIpmi{id: "79f40f9f-3e63-4639-b9d1-f32a1022f6ee"})}" -debug
DEBUG: [Invoke_Rsc] RscBasePSCmdlet.cs:90:BeginProcessing()
  Cmdlet Inputs:
    Query (String): query {clusterIpmi{id:
    Op (String): 79f40f9f-3e63-4639-b9d1-f32a1022f6ee})}
    InputProfile (Profile): DEFAULT

**Comment by guirava** [comment]
Scrubbing old issues ... I believe this is resolved, please re-open if not.
