### ISSUE TITLE
Get-RscEventSeries only works if you are an admin

### ISSUE THREAD

**Issue by SahFari** [rubrikinc/rubrik-powershell-sdk#90]
Get-RscEventSeries only works if you are an admin. It doesn’t return any values if the user has custom role

**Comment by evcheng-rubrik** [comment]
Hi @SahFari

Could you describe the error that is shown when running Get-RscEventSeries?

Thanks

**Comment by SahFari** [comment]
Hi, 
I get no results, and no errors

**Comment by evcheng-rubrik** [comment]
@SahFari would you be able to file a support ticket and reference me as the engineer?
Thanks!

**Comment by SahFari** [comment]
Hi,
Sure, I will do it on Monday.

**Comment by SahFari** [comment]
Thx Evan,
My bad! Of course, it needed permission to see the things I was asking for!

Thanks for your time, and help 😊It worked after that I gave these permissions to 2 of our custom roles:
- View system events
- View non-system events
